version: "2"

services:

  samba:
    image: dperson/samba
    restart: always
    command: '-u "${USERPASS}" -s "k500GB;/media/k500GB;yes;no;no;"'
    stdin_open: true
    tty: true
    ports:
      - 139:130
      - 445:445
    volumes:
      - /usr/share/zoneinfo/America/Argentina/Buenos_Aires:/etc/localtime
      - /mnt:/media
